<?php
declare(strict_types=1);

// HyruleCompendium SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

HyruleCompendiumUtility::setRegistrar(function (HyruleCompendiumUtility $u): void {
    $u->clean = [HyruleCompendiumClean::class, 'call'];
    $u->done = [HyruleCompendiumDone::class, 'call'];
    $u->make_error = [HyruleCompendiumMakeError::class, 'call'];
    $u->feature_add = [HyruleCompendiumFeatureAdd::class, 'call'];
    $u->feature_hook = [HyruleCompendiumFeatureHook::class, 'call'];
    $u->feature_init = [HyruleCompendiumFeatureInit::class, 'call'];
    $u->fetcher = [HyruleCompendiumFetcher::class, 'call'];
    $u->make_fetch_def = [HyruleCompendiumMakeFetchDef::class, 'call'];
    $u->make_context = [HyruleCompendiumMakeContext::class, 'call'];
    $u->make_options = [HyruleCompendiumMakeOptions::class, 'call'];
    $u->make_request = [HyruleCompendiumMakeRequest::class, 'call'];
    $u->make_response = [HyruleCompendiumMakeResponse::class, 'call'];
    $u->make_result = [HyruleCompendiumMakeResult::class, 'call'];
    $u->make_point = [HyruleCompendiumMakePoint::class, 'call'];
    $u->make_spec = [HyruleCompendiumMakeSpec::class, 'call'];
    $u->make_url = [HyruleCompendiumMakeUrl::class, 'call'];
    $u->param = [HyruleCompendiumParam::class, 'call'];
    $u->prepare_auth = [HyruleCompendiumPrepareAuth::class, 'call'];
    $u->prepare_body = [HyruleCompendiumPrepareBody::class, 'call'];
    $u->prepare_headers = [HyruleCompendiumPrepareHeaders::class, 'call'];
    $u->prepare_method = [HyruleCompendiumPrepareMethod::class, 'call'];
    $u->prepare_params = [HyruleCompendiumPrepareParams::class, 'call'];
    $u->prepare_path = [HyruleCompendiumPreparePath::class, 'call'];
    $u->prepare_query = [HyruleCompendiumPrepareQuery::class, 'call'];
    $u->graphql_body = [HyruleCompendiumGraphql::class, 'body'];
    $u->graphql_errors = [HyruleCompendiumGraphql::class, 'errors'];
    $u->result_basic = [HyruleCompendiumResultBasic::class, 'call'];
    $u->result_body = [HyruleCompendiumResultBody::class, 'call'];
    $u->result_headers = [HyruleCompendiumResultHeaders::class, 'call'];
    $u->transform_request = [HyruleCompendiumTransformRequest::class, 'call'];
    $u->transform_response = [HyruleCompendiumTransformResponse::class, 'call'];
});
